### ISSUE TITLE
[Question] Hard for reproduce with your data

### ISSUE THREAD

**Issue by Sabatrinlink123** [kylin-leo/FullProjectorCompensation#2]
Hi:
I attempted to produce results using the data you provided. However, I may have made some mistakes in certain steps, and I have some questions. If possible, I would like to receive some assistance.
	1.	For `captured` dataset, using 15 images seems to yield correctly compensated images, but when I change the number of training sets to 25, as described in the paper, mosaic artifacts start to appear.
	2.	The appearance of black borders is confusing to me. Why were 96x72 black borders added to the projector input? I don’t quite understand this, and I couldn’t find an explanation for it in the paper.
	3.	No matter how I change the training images for the `captured_1` dataset, the compensated images always result in the same mosaic artifacts. I’m not sure if I’m doing something wrong.
<img width="190" alt="image" src="https://github.com/user-attachments/assets/c1a770d5-9548-4a97-99f4-021d4d0aaf04">

**Comment by kylin-leo** [comment]
The black border is used for optical flow estimation. However, GMA cannot handle situations where one image has a black border and the other does not.
I have not encountered mosaic artifacts before. My assumption is that this issue occurs when optimization fails to converge and stuck in local minima. To ensure stable parameter estimation, I recommend using some filtering methods like moving average.

**Comment by Sabatrinlink123** [comment]
Hi, thanks for the feedback.
